### ISSUE TITLE
Change input language via a keybind

### ISSUE THREAD

**Issue by xDarksome** [pop-os/cosmic-comp#103]
What's the state of this?

**Comment by Drakulix** [comment]
I am pretty sure @ids1024 has made some progress on cosmic-comp being able to reload input-configuration (including a PR to smithay to support this functionality in our stack: https://github.com/Smithay/smithay/pull/1020).
So that should come hopefully pretty soon and adding the ability to toggle this functionality via key-bindings shouldn't be too hard once that is there.

**Comment by ids1024** [comment]
Actually, language switching keybindings are handed by libxkbcommon, so this already works. If you add multiple layouts to `.local/state/cosmic-comp/inputs.ron`.

What needs a bit more work is being able to dynamically change the list of layouts without restarting the compositor.

**Comment by xDarksome** [comment]
@ids1024 what's the default keybinding to switch between languages in libxkbcommon? Is there a way to configure it?

**Comment by xDarksome** [comment]
Works, thanks!
