### ISSUE TITLE
[Question] "Fake resolution" in games when using fractional scaling

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-comp#1096]
This is mostly because I want to understand what is happening with Cosmic Comp when playing a game on full screen and having fractional scaling on, or actually know if it's a bug that hasn't been reported yet. I know more or less that when applying fractional scaling, UI elements are supposed to be 2x their size, but then get downscaled. For example, in my case, when I set my laptop screen to 1920x1080 and then scale to 125%, I get a 1536x864 viewing area, with a larger mouse cursor, and the like, which then gets resized down.

However, I don't really understand why, if the setting to have X11 apps scale by themselves, video games use a gigantic "fake" resolution of 3072x1728. Essentially 1536x864 times 2, and not what I would expect, which is 1920x1080. I know that in reality, the game _is_ rendering at 1920x1080, because I get zero performance penalty compared to setting my resolution to 100% scale at 1080p, yet the game thinks the screen resolution is much larger.

Is this a bug in Cosmic Comp, or is this expected behavior? Does this have to do with the fact most games running on Wine still use XWayland? Does the native Wayland version of Wine change any of this?

I'm mostly asking because when I saw my games running at huge resolutions, I had concerns that my laptop would not be able to run them at all, but then I figured out the game was actually playing at native resolution, yet showing that other fake resolution in the settings. Very confusing.

**Comment by Drakulix** [comment]
> Is this a bug in Cosmic Comp, or is this expected behavior? Does this have to do with the fact most games running on Wine still use XWayland? Does the native Wayland version of Wine change any of this?

Yes, yes and yes.

> I know that in reality, the game is rendering at 1920x1080

You should still select 1920x1080 in the game, otherwise you might loose performance. Selecting the right resolution should result in a 1:1 mapping of pixels to your output.

So yes, all of this is expected. Because of how X11 works, we can only scale in integer scales and we can only send a single scaling value for all outputs. (See https://github.com/pop-os/cosmic-comp/pull/779 for more technical background.)

So if you tell cosmic-comp to let X11 scale itself, we give it the next integer scale (2x) and then need to adjust output sizes, so that they are still correct relative to each other and scale down the 2x image from X11 apps to actually 125%.

This is how you end up with two times 1536x864.

**Comment by hfc2x** [comment]
I see, thanks for your answer.

> You should still select 1920x1080 in the game, otherwise you might loose performance. Selecting the right resolution should result in a 1:1 mapping of pixels to your output.

I tried doing this at first, because I thought the gigantic resolution would give me performance issues, and when setting the game resolution to 1920x1080, I get exactly what happens to [this other person](https://github.com/pop-os/cosmic-comp/issues/484#issuecomment-2361042652), where the mouse cursor is completely misaligned with where the game thinks I'm clicking. But seeing I was not losing any performance, I just chose to keep it the way it was.

So, because this seems to be an X11 issue, I'm closing this as my question has been answered.
