### ISSUE TITLE
Tiling window movement still active when `Shift` key is released

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-comp#115]
If we move a window with `Shift` + `Super` but release from `Shift` so that `Super` is still pressed, the zoomed-out tiling movement mode is still active. We'd prefer to have the mode exit and zoom back in if either key is released.

There's an interesting case here where the arrow keys will move window focus within the mode, but it will also focus on an empty workspace, which is undesired for us in the context of moving a window. The UX side also thinks we'd prefer to have the movement "mode" end before changing window focus with `Super` and the arrow keys.

**Comment by Drakulix** [comment]
The logic is currently not specifically looking for "Super", but because key bindings can be arbitrarily configured for "all modifiers being released, that were used to engage the first move action". (Which happen to be Super+Shift in the default config.)

I guess this logic should be changed then to "**any** modifier being released, that was used to engage the first move action" to achieve this?
