### ISSUE TITLE
Launching cosmic-comp kms mode race condition

### ISSUE THREAD

**Issue by h1771t** [pop-os/cosmic-comp#15]
When launching cosmic-comp from the console in kms mode, I sometimes get the error seen as in attached log
[cosmic-comp.log](https://github.com/pop-os/cosmic-comp/files/8834621/cosmic-comp.log)

`thread 'main' panicked at 'Backend initialized without output', src/input/mod.rs:148:34`

Seems like:
> src/backend/kms/mod.rs
> pub fn init_backend
> let libinput_event_source = event_loop
> state.process_input_event(event);

Can get called sometimes even before the display is initialized later in the same function, causing this line to not find an initialized display and therefore `.expect()` to trigger

> src/input/mod.rs
> impl State {
> pub fn process_input_event
> .expect("Backend initialized without output")

**Comment by Drakulix** [comment]
Work is underway to fix this:
- [x] https://github.com/Smithay/calloop/pull/102
- [ ] https://github.com/Smithay/smithay/pull/638

The issue is, that right now devices are not added, when initializing the backend, like they are supposed to
https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/backend/kms/mod.rs#L272-L276
because this check always returns `false` immediately after creation of the session: https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/backend/kms/mod.rs#L282-L284 .

As a result it is racy if first the initial input events are dispatched or if the outputs are added to the compositor.
Otherwise the assumption, that there is always an output, when they are input devices, should hold true all the time, as cosmic-comp is supposed to exit anyway, if it cannot detect any outputs.
