### ISSUE TITLE
Closed X11 windows persist

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#162]
When closing X11 windows, often they will stick around for a while, even after the spawning process has exited. I've replicated this with QEMU and Steam.

**Comment by Drakulix** [comment]
We should get an `unmap`-request from X11 immediately, can you confirm that this does happen? https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/xwayland.rs#L202

This callback is what calls `Workspace::unmap`, otherwise the window will get garbage-collected (probably much later) once the compositor notices that the accompanying `wl_surface` is dead. And I am not even sure that this will always happen, given that Xwayland heavily re-uses wayland resources. So the window might stick around in those cases until a new X11 window is spawned.
