### ISSUE TITLE
Swapping: swap a single window with any window in a stack

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#170]
Current behavior:

Single window > Super X > swap with stack > can only swap with entire stack

Desired behavior:

Single window > Super X > swap moves across the tabs in stack > swap individual window (swapping a stacked window to a stacked window does this currently)

Additional feature: 

When reaching the last window in the stack, one more move highlights the entire stack. This allows an entire stack to be swapped without adding Super + U.

**Comment by Drakulix** [comment]
Current behaviour should be fixed with https://github.com/pop-os/cosmic-comp/commit/5aeb0f63b102d3ddf2d32cde0098aa169c3784f2.

Regarding the additional feature this feels a bit inconsistent and arbitrary to me. I am not opposed to implement it, but maybe we can instead make the Super+U/I shortcuts more discoverable somehow?

**Comment by WatchMkr** [comment]
Agreed, let's explore making Super+U/I more discoverable with Maria.

**Comment by maria-komarova** [comment]
Maybe we can go back to showing the shortcut in the tooltip, just a different shortcut. We can show that Super + U would swap with stack when the target window is part of the stack. 
![1300 - swap-with-stack-indicator](https://github.com/pop-os/cosmic-comp/assets/57502897/e2bd4c9f-f8f8-4be2-abca-d5c17bad3ec1)
