### ISSUE TITLE
Design discussion: Stacks and Floating Windows

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#262]
Window stacks are a unique and useful feature but not properly leveraged for our floating users (65%). Let's fix that.

With floating windows, it's not possible to add a window to the stack. Improvement ideas:
- Dragging a window to the stack header offers to add it to the stack.
- When grabbing and dragging to remove a window from a stack, allow cancelling by moving the cursor back over the stack
- A new-tab (+) icon to the right of the tab in a stack. Clicking this icon opens the launcher to add an app to the stack. In this case, what do we do with already-open apps typically in the Launcher? Not show them (only new instances)? Move an open instance into the stack (would probably be weird).
- When an app-stack is focused, add apps that are newly launched to the stack (same as tiling).

Creating a stack should be added to window controls. 
- Once stacked, the window control would change to something representing removing the window from the stack.
- Window control responsiveness: how do window controls collapse when the window becomes narrow?

Stack appearance
- The gradient in the tab makes the close button appear on a higher level than the tab it's on. Try with multiple windows stacked. It appears that the close button is attached to the wrong tab.
- Stack tabs need an on-hover visual distinction
- For apps with server-side decorations (slack, mattermost, gimp, etc.), activating stacks removes the original header and replaces it with the smaller stack UI. For the user, where did window controls (other than close) go and why does the header become smaller? 
  - We could stack the UI's but this would take a lot of space. 
  - Window controls could go in tabs but this would make them different than other apps. 
  - If we don't want to stack the UIs, we could find a middle ground between the header and stack UI height that is the same so the window header size doesn't change when users change between header and stack UIs.

**Comment by Drakulix** [comment]
> Dragging a window to the stack header offers to add it to the stack.

This feels natural, the biggest question here is design/visuals/animations. The current code is already quite complex, I would hope for a minimalist approach. E.g. showing the new tab shaded differently (possibly using accent color to signify the action?) and making the window slightly transparent?

> When grabbing and dragging to remove a window from a stack, allow cancelling by moving the cursor back over the stack

I think this goes hand in hand with the previous suggestion, we could re-use the same visuals. From a code perspective there is no difference between moving in and out and cancelling. This would then also allow to move tabs by dragging.

> A new-tab (+) icon to the right of the tab in a stack. Clicking this icon opens the launcher to add an app to the stack. In this case, what do we do with already-open apps typically in the Launcher? Not show them (only new instances)? Move an open instance into the stack (would probably be weird).

This is a little complicated from a code perspective, as this context would need to be passed to the launcher. Doable, but perhaps this is unnecessary, if dragging is supported?
Alternatively we could add a way to simply select an existing window to move it into the stack in the compositor?

> When an app-stack is focused, add apps that are newly launched to the stack (same as tiling).

We should do this for consistency reasons alone in my opinion.


> Creating a stack should be added to window controls.

If I don't misunderstand the intent, we can only really do this for server-side decorated windows.

> The gradient in the tab makes the close button appear on a higher level than the tab it's on. Try with multiple windows stacked. It appears that the close button is attached to the wrong tab.

The gradients purpose is simply to fade-out the title to the edge of the tab. I think this is simply an issue of the theme color not being applied correctly here.

> Window controls could go in tabs but this would make them different than other apps.

Which controls are we talking about here? Maximize and minimize don't really make sense in the context of a stacked app anyway, no?

**Comment by loligans** [comment]
This is all very interesting!

One thing I'd like to add is that it would be great to cycle through the tabs by using a configurable hotkey and or scroll wheel. Similar to how you can cycle tabs on Firefox with `Alt + <number>`.

**Comment by Vaisakhkm2625** [comment]
> This is all very interesting!
> 
> One thing I'd like to add is that it would be great to cycle through the tabs by using a configurable hotkey and or scroll wheel. Similar to how you can cycle tabs on Firefox with `Alt + <number>`.
if doing tabbed interfaces can't live without a <modifier>+<num> combo in a tabbed interface... +1 for that...

**Comment by spacelike** [comment]
>When an app-stack is focused, add apps that are newly launched to the stack (same as tiling).

In my opinion this is an essential features for tabbing. That's how i3's tab mode behaves and I use it a lot.
Comparing that to other floating WM's which have supported tabs in the past I've seen many comments from users who say they tend to never use the feature because it's not worth it to have to drag each window to be a tab every time.
Having some option to capture new windows as tabs automatically makes all the difference, and is how web browsers work after all.

**Comment by alaestor** [comment]
I absolutely love this and some of these ideas, or things similar to them, are practically mandatory if stacks are to be accessible and intuitive for many users. I felt that I should throw my two cents in regarding one point here, and offer a perspective that may be useful while designing and discussing potential features.

> Dragging a window to the stack header offers to add it to the stack.

Perhaps could this be enabled while holding a modifier key? Or a hover-delay with animations?

Allowing the user to intent signal intent is important for UX. As an extreme example: the Windows shake gesture wouldn't have been annoying if you had to hold a key to trigger it... A lesson I learned from Windows is that fighting gesture and position based features can be annoying when simply trying to free-form position a floating window. One of the things I love about Power Toys' Fancy Zones in Win10 is that zone snapping is enabled while holding down a key; this let me to disable the default monitor edge snapping/filling etc and rely purely on the explicit, opt-in behavior of zones (which was a bit of a selling point for me, on top of all the customization it offers). 

Dragging on and off of tab lists is pretty well understood by most people thanks to browsers and similar apps, but people rarely have more than one or two windows of this type open at a single time. If I have three, four, ... or a dozen, then avoiding accidental stacking can become a "problem". Even with fewer stacks, it's yet another thing I'd have to keep in mind while dragging windows around. If they only stacked if I dragged while holding a key, then it becomes a non-issue. This could also be solved by requiring a hover-delay before stacking would occur upon drag release; preferably with some UI change, similar to grouping app icons on most android phone UIs. The delay solution could be both intuitive and aesthetically pleasing, while still confirming user intent. Configurability would also be desirable, such as the hover duration in ms.

I hope you pardon my long-winded elaboration. I felt it may be useful since this kind of polish is something that can easily be overlooked, and because this general concept of being mindful of user intent can be critical for making a good user experience; particularly graphical experiences.

**Comment by foodmonkey** [comment]
OK - so using a floating window from an application - pushing it to the stack - keep inter and intra application communication open and synchronised 

and yes ok - this drops right into the window tiling manager vs app window management

as devils advocate - i'm saying the multiple window effect in vs code - (i'm now using zed - just to be clear) but that whole detaching an edit window from vscode was not easy or intuitive - is it a thing that you want cosmic to do or provide a framework for an app like zed to do so
