### ISSUE TITLE
Feature: BT.2020 colour space

### ISSUE THREAD

**Issue by elahn** [pop-os/cosmic-comp#3]
A wonderful option would be for the compositor to always output in BT.2020 colour space. RGB surfaces would be mapped to BT.2020. This way, windowed/embedded HDR content would always display correctly.

A possibility to run filters on the output would be great as well. e.g. applying a gamma curve to the whole screen, lowering "brightness" to reduce migraine pain. *(As an aside, migraine is the third most common disease globally, affecting one in every seven people.)*

Obviously, this is not important at this stage of development but hopefully, the design can accommodate this future.

**Comment by Drakulix** [comment]
Thanks for reaching out! :wave: Proper color management is definitely an important goal for this project.

However HDR on Linux is still a relatively new topic and the discussion on how do that on wayland is still very active:
- https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14
- or for a more broad overview: https://www.collabora.com/news-and-blog/blog/2020/11/19/developing-wayland-color-management-and-high-dynamic-range/

cosmic-comp will likely implement, what is coming out of this discussion, which will define how clients can interact with the compositor to communicate their color space and properties.

On the server side, mixed mode content (HDR windows alongside non-HDR windows) is an explicit design-goal of the protocols, so cosmic-comp *should* be able to provide BT.2020 support.

Additionally a feature like gnome's "Night Light" is going to be implemented for sure, likely through support of the [wlr-gamma-control](https://wayland.app/protocols/wlr-gamma-control-unstable-v1) protocol, which would allow different clients to do more in-depth customization of the gamma values of a given output.

I cannot make promises how customizable each aspect of the whole rendering-pipeline will be, custom filters is definitely not an easy topic and we will likely focus on getting the output correct instead of very flexible in the first place. But each more specific feature you have requested is definitely in scope, I just cannot tell you at which stage of the product cycle support will be implemented.

**Comment by jokeyrhyme** [comment]
Related to #764
