### ISSUE TITLE
Cyberpunk 2077 does not show if started fullscreen

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-comp#316]
```
Operating System: Fedora Linux 41
KDE Plasma Version: 5.93.0
KDE Frameworks Version: 5.249.0
Qt Version: 6.6.2
Kernel Version: 6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 20 × 13th Gen Intel® CoreT i7-13700H
Memory: 31.0 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: ROG Zephyrus M16 GU604VY_GU604VY_00130747B
System Version: 1.0
```

Ignore that I'm using KDE above, I test also cosmic daily/weekly. My system also includes an RTX 4070 (hybrid). Also ignore that I'm using nouveau - I test both nouveau and proprietary 550.x.x.

The issue here is that if Cyberpunk is set to fullscreen or borderless window, then closed and reopened it shows nothing. I can hear the game running fine however. This happens only if the game is started in fullscreen/borderless mode. If I start in windowed mode then set fullscreen it is fine.

The game is being run on the nvidia output.

The same also happens in Wreckfest. And it happens across all 3 laptops I have.

Unsure what other info would help here.

**Comment by ids1024** [comment]
What version of cosmic-comp is this with? https://github.com/pop-os/cosmic-comp/pull/278 changes various things around dual GPU systems, and was just merged. If you're on an older version, it might fix the issue; if you're testing the latest commit, and it was working earlier, that might have caused the issue.

Issues with fullscreen could be related to direct scanout. Though it's interesting that it depends on whether or not it started in fullscreen mode. Maybe based on the dmabuf feedback when the window is initially opened; though I'm not sure how that ends up working through both XWayland and Wine.

I'd also look to see if any errors are logged to `journalctl`.

**Comment by flukejones** [comment]
I knew I forgot something. I was testing that branch. Hmm, I think also that it was a problem previously before that work but I never got round to filing the bug.

I do need to check:
- laptop with igpu connected output (was stuck with my nvidia-only output laptop for a bit)
- internal screen only

Once I finish up my tasks at work I'll check these and see if I can get any decent log info.

**Comment by flukejones** [comment]
It looks like the issue is only with nvidia dgpu outputs

**Comment by gabriele2000** [comment]
@ids1024 I have a similar issue in specific ways.
- Here's the log of journalctl 
[journalctl.log](https://github.com/pop-os/cosmic-comp/files/14754908/journalctl.log)

- First issue: The Crew 1 is just a black screen since yesterday's update to cosmic- packages [Video 1](https://youtu.be/A50kTFik9HA)

- Second issue: Switching workspaces or doing something remotely related to changing focus leads to the first issue [Video 2](https://youtu.be/0PReL5F2VG8)

Context on the first issue:
Proton's FSR patch, using FSHack, makes the game render at whatever resolution you want, then the game's DPI are scaled as if you were using the native resolution of your screen.

I use 720p that FSR will upscale at 1080p.
That leads to the game loading then quickly resizing the window or something like that, you can see a quickly changing window before the game renders (in the second video, in the first video the game just fails to render)
