### ISSUE TITLE
xwayland: activating a window in a different workspace doesn't focus the window

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-comp#355]
To reproduce:

* Open Discord (xwayland) in one workspace (could be any xwayland app)
* Open OnlyOffice (xwayland) in another workspace (could be any xwayland app)
* Focus Discord, then click on OnlyOffice using the app list applet
* Workspace switches, but the app itself cannot be interacted with (this can be fixed by clicking the icon in the app list applet again)

This could be an app-list issue, or a cosmic-comp issue

**Comment by coryc96** [comment]
This can be reproduced without the applist also. It appears to happen a lot if the xwayland apps are "overlapping" each other on two different workspaces. So for example, 
Workspace 1: Cosmic Term | Spotify
Workspace 2: Cosmic Files | Ferdium
Changing workspaces between these mean that both Spotify and Ferdium will not be interactable (until clicking it in the app list, as you mentioned)

But if you swap the position so they aren't overlapping, then they both work.
Workspace 1: Cosmic Term | Spotify
Workspace 2: Ferdium | Cosmic Files

This works as expected. I think there's another piece of the puzzle that I'm missing because I've seen extra unpredictable behavior similar to this, but I can't reproduce it. Either way, it seems to be workspace switching is not properly or fully changing the workspace context the user is in.

**Comment by ryanabx** [comment]
A fun way to debug this is by playing an xwayland game with audio, that stops playing audio when unfocused. Surprisingly a lot of the time the xwayland window is focused, even when on different workspaces.

**Comment by ryanabx** [comment]
Another way to activate focus when it shouldn't be activated:

* Open steam and a windowed xwayland game
* Focus xwayland game, then focus steam
* Move steam window around by clicking and dragging titlebar
* While the steam window is moving around, focus will be given to the game
