### ISSUE TITLE
High CPU usage when idling, low cpu usage when cursor is moving

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#356]
I have alacritty and firefox open.
When idling and nothing is happening, `cosmic-comp` uses 5% of my cpu (which is 100% of core).
But when I start wiggling the mouse cursor, `cosmic-comp`'s cpu usage drops!
Here is a screenshot, you can tell when exactly I started moving the cursor (I was trying to recreate the github issue that you see in the screenshot, but I experienced the opposite of that issue).
![screenshot-2024-03-14-03-52-31](https://github.com/pop-os/cosmic-comp/assets/2222199/0c1f582e-d77f-4cad-bcd7-ae6fc7da3a27)

Edit: after some more testing, this seems to be caused by Firefox trying to render a page! This does not happen with Google Chrome.

**Comment by jacobgkau** [comment]
I'm also commonly having my CPU keep going to 100% over and over (and spinning up my fans) because cosmic-comp is pinning a core, even when I'm not touching the system at all (this is on a serw13).

![screenshot-2024-05-08-03-14-22](https://github.com/pop-os/cosmic-comp/assets/7199422/1caca189-1a44-45b5-8da8-678de9e35914)

cosmic-comp's not outputting anything to the logs when this is happening. I do have a lot of windows open across a lot of workspaces, and many of them are Firefox windows, so it could be the same issue.

I do not see moving the mouse cursor consistently get the issue to stop happening, though.

**Comment by Drakulix** [comment]
I am pretty sure this is related to poor frame-callback pacing/timing in cosmic-comp.
