### ISSUE TITLE
Desktop: It also stops working when the monitor is turned off.

### ISSUE THREAD

**Issue by songww** [pop-os/cosmic-comp#57]
Last logs:
```
Jan 07 07:18:52.336 INFO New device "event0", smithay_module: backend_libinput
Jan 07 07:18:52.344 INFO New device "event1", smithay_module: backend_libinput
Jan 07 07:18:52.353 INFO New device "event7", smithay_module: backend_libinput
Jan 07 07:18:55.732 INFO Device changed: #57856, smithay_module: backend_udev
Jan 07 07:18:55.833 INFO Dropping device: Some("/dev/dri/card0"), smithay_module: backend_drm
Jan 07 07:18:55.854 INFO Device changed: #57856, smithay_module: backend_udev
Jan 07 07:18:55.879 INFO Shutting down
Jan 07 07:18:55.880 INFO Dropping device: Some("/dev/dri/card0"), smithay_module: backend_drm
```

Seems caused by: https://github.com/pop-os/cosmic-comp/blob/52561496ac47c31a15f8004e008dc157dc6f4787/src/main.rs#L58

**Comment by Drakulix** [comment]
Yes, this was intentional in the beginning, as starting the desktop environment without any outputs usually indicated, that something went wrong initializing the graphics devices. Of course this is not useful in day-to-day use, though this needs some plumbing to get initialization-errors to still properly shut down the DE, so I'll leave this open until I get to it.

**Comment by XV-02** [comment]
This issue is still relevant.

If I have a desktop with a single external display, which is off, I can log into to a Cosmic session while the display is off. When the display is turned on, the session appears to correctly instance, and largely seems to behave in a manner comparable to a Gnome session.

If I am in the middle of a Cosmic session, and turn the display off, the session does not recover when the display is turned on again.

**Comment by BobbyByrne** [comment]
Single monitor and I'm using a KVM to switch between personal desktop and work laptop. My situation is a bit more complicated since I'm not only unplugging my monitor, but I'm also unplugging half of the usb devices as well lol.

Let me know if there's anything I can do to help test.
