### ISSUE TITLE
Application unresponse due to not getting frame callback when moved on hotplug

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#58]
* Run `cosmic-comp` with more than one monitor
* Open `gnome-terminal`, `foot`, etc. on one monitor
* Disable the monitor it is open on in `wdisplays`
* The workspace the application was on is moved to the display that is still enabled, but switching to that, the application seems slow to respond to input

Looking at `WAYLAND_DEBUG` logs of `foot`, it seems it isn't receiving a regular `frame` callback when this issue occurs, unlike when the application is running normally.

Looking at the code involved in sending frame callbacks, maybe the "primary scanout output" for the surface isn't being changed correctly?

**Comment by Drakulix** [comment]
Do they get an output_enter event when the workspace is moved? In any case, super useful observation, I guess the workspace move logic is flawed here.

**Comment by ids1024** [comment]
Hm, turning off my external monitor (while the internal monitor isn't enabled) the internal monitor starts working, but all my workspaces disappear into the void instead of moving. The applications seem to still be running though.

**Comment by wash2** [comment]
I think this may also be affecting cosmic-panel. When I unplug a monitor with the panel running, it seems to get stuck when swapping buffers.

**Comment by ids1024** [comment]
It is expected that occluded windows will not receive frame callbacks. `EglSwapBuffers` thus blocks potentially indefinitely, since it blocks on as frame callback (as implemented in Mesa), unless `EglSwapInterval` is set to `0`.

I guess the layer shell surface should receive `closed` from the compositor if the output it's on is disconnected? Not sure how that impacts Mesa's blocking on the frame callback. Probably best to set the swap interval to 0 and handle frame callbacks to drive rendering.

**Comment by Drakulix** [comment]
> I guess the layer shell surface should receive closed from the compositor if the output it's on is disconnected? 

I pushed a commit, that does this, given it is definitely a good idea and a miss on my side.
But I am still investigating the original issue more.

**Comment by ids1024** [comment]
I seem to be consistently seeing applications not receive frame callbacks when dragged to another monitor as well now, which wasn't previously happening.

**Comment by ids1024** [comment]
It seems `default_primary_scanout_output_compare` is returning the `current_output`, since it has a larger `visible_area`. It seems to work better replacing that callback with one that always returns the `new_output`. Cosmic-comp seems to only show windows on the new output when moved, so I think that would be correct?

But presumably `visible_area` should not-have a non-zero value for more than one output when it clearly is only present on one, so something isn't right there. I guess it's not being cleared to 0 when a window is no longer visible on that output at all?

**Comment by Drakulix** [comment]
>  It seems to work better replacing that callback with one that always returns the new_output. Cosmic-comp seems to only show windows on the new output when moved, so I think that would be correct?

That is the case for the OutputBound workspaces, not for global workspaces.

> It seems default_primary_scanout_output_compare is returning the current_output, since it has a larger visible_area.

However that is part of the issue, because cosmic-comp is [already filtering the windows for outputs](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/state.rs#L409-L411).
So if one output would want to send frame callbacks to the window, but it returns a different primary output, it won't get them. And the other output, that would be returned by the primary output, will not contain the window to begin with.

So we need to make sure the primary scanout output is always matching with one of the outputs of the workspace the window is bound to.
However in case of global outputs there might be multiple options and in those cases, we want to compare by `visible_area` to make sure the window gets frame-callbacks matching the refresh rate of the output most of its contents are displayed on.
If we send the frame callback for the wrong one, we get a mismatch in framerate and if we end up sending frame-callbacks for both, we would flood the window with unnecessary frame requests.

**Comment by ids1024** [comment]
Ah right, I noticed that when I tried `Global` workspaces. We'll need to discuss the behavior here more because it isn't entirely clear. Like part of your window just no longer rendering once you stop dragging is a bit weird. But that's a different matter.

The weird thing here is that I'm seeing `visible_area` greater for the old output even when the window is entirely within the new output. So I don't entirely follow the logic for how it's ending up that way but presumably that number should be `0`.

**Comment by Drakulix** [comment]
Looking at the [function responsible for updating the output](https://smithay.github.io/smithay/src/smithay/backend/renderer/element/mod.rs.html#169-243), the issue seems to simply be, that the old output is never cleared. So if the visible area turns out to be smaller (or equal for that matter, which should apply to moved windows that keep their size), it is never switched over.

And that is not really a bug, given that `send_frames` might be called from multiple render-calls of different outputs. So the comparison function can never be sure the old output is actually not displaying anything any more.

It seems to me the simplest option to fix this is by replacing the [`default_primary_scanout_output_compare`](https://smithay.github.io/smithay/smithay/backend/renderer/element/fn.default_primary_scanout_output_compare.html#), that cosmic-comp is currently using.

Essentially the closure would need to be extended by the information on which outputs the surface is actually visible (which we can easily query using [`Workspace::outputs_for_element`]) and dismiss any of the two outputs provided for comparison, if it is not included in the set. Only if both are, it would fall back to `default_primary_scanout_output_compare`, which then proceeds to do the visible_area compare.

**Comment by ids1024** [comment]
> Though I wonder, how the visible area actually turns out to be smaller. The compare-function prefers a new-output, if the result is equal and assuming the windows is just moved - not resized - it should get the new output... Anyway, there is no harm to make the comparison function more specific.

If you look at the doc comment and implementation for `default_primary_scanout_output_compare` it "will prefer the next output when the visible portion of the element on screen is at least twice the size of the current visible portion." So when it's the same, it sticks with the old output because it's less than twice the previous value.

I'm not entirely sure why it's definite that way.
