### ISSUE TITLE
Scale factor causes the cursor to be limited to one screen

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#71]
My setup:
a laptop with an external monitor on the USB C port.

I changed the scaling factor for all my outputs from 1.0 to 1.5. Then I noticed that my cursor can not leave the external monitor. The cursor can move from the built-in screen to the external one, but not from the external screen to the built-in one.

If I switch focus to a window that is on the built-in screen the cursor would appear on that screen and I can move it back to the external screen, but then I can't move it back to the built-in screen (unless I use the keyboard and move the focus to a window on that screen).

If I return all the scaling factors to 1.0, then the cursor is free to move between the screens.

I know cosmic-comp is not ready but I figured this is odd enough to report.

**Comment by Drakulix** [comment]
I assume you have set the scaling factor by editing `~/.local/state/cosmic-comp/outputs.ron`, is that correct?

Have you tried setting up the scaling factor with a config tool like [`wdisplays`](https://github.com/luispabon/wdisplays) instead?

Setting a scale factor causes the output to have a different "virtual resolution", causing it to take up less "space" in the global coordinate space of the compositor.
As such you need to adjust the "position" key in the config file, to make then adjacent again.

E.g. if you have a screen of 1920x1080 resolution and you set a scaling factor of 1.5 the virtual resolution will drop to 1280x720. So the position of the next output on the right would need to be (1280, 0).

That is much easier visible and configurable using a graphical tool, like wdisplays. Otherwise you would run into problems similar to the one you are describing.

As such I would not necessarily flag this as an issue of cosmic-comp, given that the config file is meant (at least for now) for internal use. The `wlr-output-configuration`-protocol (which wdisplays uses for configuration) on the other hand is the *public* interface meant to be used by users.

**Comment by hojjatabdollahi** [comment]
You're right. `wdisplays`  works just fine. I should've known better! Thanks.
