### ISSUE TITLE
[BUG] X11 scaling report bigger monitor dimensions

### ISSUE THREAD

**Issue by KoreshKrasa** [pop-os/cosmic-comp#808]
I have 1440p monitor but with x11 scaling enabled xwayland clients see max dimensions bigger than monitor resolution
![screenshot-2024-09-03-19-10-43](https://github.com/user-attachments/assets/24169780-65c3-41a9-a41e-66865a251f20)

**Comment by Drakulix** [comment]
Do you have a fractional scale set? If so, this is expected.

X11 scales only work on integer scales, so e.g. if you have a scale of 150% set, Xwayland will be scaled at 200% and be downscaled as necessary to fit.

As long as you set your resolution to match your actual output size, the scaling will cancel itself out, causing a 1:1 mapping of the pixels drawn by the game to your output.

**Comment by Drakulix** [comment]
There is sadly no way to avoid this, if you don't want blurry apps on 125%. Xwayland simply doesn't allow for fractional scales. That is why there is an option to choose, neither variant is a good fit for every single scenario.

**Comment by Koranir** [comment]
> There is sadly no way to avoid this, if you don't want blurry apps on 125%. Xwayland simply doesn't allow for fractional scales. That is why there is an option to choose, neither variant is a good fit for every single scenario, but that is an inherent problem of how X11 works.

I would expect that rather than scaling at 200% and then down-sampling, the xwayland window would have an integer scaling of 100% and the client application given a resolution that is equal to the actual pixel dimensions of the window on-screen. This seems to be what Plasma is doing, and it does not suffer from clients having these huge resolutions.

Is there something I'm missing here?

**Comment by Drakulix** [comment]
> I would expect that rather than scaling at 200% and then down-sampling, the xwayland window would have an integer scaling of 100% and the client application given a resolution that is equal to the actual pixel dimensions of the window on-screen. This seems to be what Plasma is doing, and it does not suffer from clients having these huge resolutions.
> 
> Is there something I'm missing here?

The only difference here is that they opt to round to the next lower integer scale value (100%) instead of the next higher one (200%) like COSMIC does. In general this means apps look smaller than their wayland-native counterparts, while we opt for downscaling to have them be non-blurry and relatively sized correctly.
