### ISSUE TITLE
Focused window frame appears over popups

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#89]
In floating mode, popups opened at the edge of a window end up covered by the border drawn around the window. In tiling mode it instead prefers to open the popup within the tile, though presumably the same issue world occur if the tile was too small relative to the popup.

This seems a bit awkward to deal with since drawing the window an popups involves several layers of things implementing `AsRenderElements` before the implementation from `smithay::desktop::Window` is eventually called...

I guess this would be an issue with SSDs too?

Not sure the best solution here. Though it may be good if the logic for drawing a window with a `IndicatorShader` around it could be de-duplicated.

**Comment by Drakulix** [comment]
Oh boy, yeah popup render-order is kind of an annoying problem. Essentially we would like popups to sit on a layer over everything (except layer-shell surfaces on the Overlay layer, whos popups need to be displayed at the very top of course). So the *correct* fix for this is to split apart the `Window`'s `AsRenderElements` implementation into separate functions, that return the windows elements and any popups elements. At that point we can collect the popups separately inside the `Workspace::render_output`.

Given the actual [implementation](https://smithay.github.io/smithay/src/smithay/desktop/space/wayland/window.rs.html#104-128) of [`render_elements`] for smithays [`Window`] type is basically just a wrapper around [`render_elements_from_surface_tree`] for both it's toplevel surface and all popups accumulated via [`PopupManager::popups_for_surface`], none of this requires any changes to smithay itself (everything is public).

So instead of calling those (and relying on the `AsRenderElements`-trait) `CosmicSurface` could have two separate functions:
- `toplevel_render_elements`
- `popup_render_elements`

Those functions could bubble up through [`CosmicWindow`] and [`CosmicStack`] up to [`CosmicMapped`], where then [`Workspace::render_output`] can take over and split everything neatly apart.

**Comment by ids1024** [comment]
> Those functions could bubble up through CosmicWindow and CosmicStack up to CosmicMapped, where then [Workspace::render_output] can take over and split everything neatly apart.

Doable enough, though a bit annoying to have to duplicate that at each of this levels.

> Note: An alternative and easy solution would be to order the indicator below the window. But this is against the design, which is meant to round the corners of the image by overlaying the border.

Hm, is the indicator being over the window also preventing `DrmCompositor` from being able to scanout the focused window in an overlay plane?

**Comment by Drakulix** [comment]
> Hm, is the indicator being over the window also preventing `DrmCompositor` from being able to scanout the focused window in an overlay plane?

Yes, that is sadly a result of this. But on the bright side, overlay planes are under-used and not very flexible on many desktop gpus anyway.

And if multiple windows are visible, those are still able to be scanned out, which provides the same efficiency gains than scanning out the focused one.

**Comment by ids1024** [comment]
> Popups of tiled windows should also go above floating windows, which they currently don't.

If every normal desktop compositor should behave this way, some kind of improvement in Smithay would be ideal, though I don't know what that would look like. (Keep `AsRenderElement` unchanged, but have a separate trait for things that have popups? a bit awkward.)

With `toplevel_render_elements` and `popup_render_elements`, this seems to lead to some duplication, since those both involve iterating over all child elements positioned correctly. Maybe simpler to have a single function returning two vecs? Or a vec of pairs.

`FloatingLayout::render_output` and `TilingLayout::render_output` would also need to be split into toplevel/popup variants, if we want to make popups of tiled windows appear over floating windows.

**Comment by Drakulix** [comment]
> Maybe simpler to have a single function returning two vecs? Or a vec of pairs.

I think this is a good idea, that we actually should extend to other functions. We certainly don't want to have two times the complexity of `TilingLayout::render_output` in our code (and that beast is bound to get even more complex with mouse-tiling), so I think these should also return two `Vec`s instead and then merge everything in `Workspace::render_output`. That would keep the amount of changes to a minimum.
