### ISSUE TITLE
Using system clipboard inside a fullscreen Helix editor makes the Alacritty window to reposition itself

### ISSUE THREAD

**Issue by xDarksome** [pop-os/cosmic-comp#99]
So, I have the following setup: running [helix](https://github.com/helix-editor/helix) editor inside an [alacritty](https://github.com/alacritty/alacritty) terminal window.

Copy-pasting commands inside a fullscreen Alacritty window works fine. (`Ctrl-Shift-C` -> `Ctrl-Shift-V` inside the prompt)

Copy-pasting text via Alacritty shortcuts inside a fullscreen Alacritty window running Helix works as well.

However, when I try to use bultin Helix commands which manipulate the system clipboard inside a _fullscreen_ Alacritty window, for some reason, the window gets shifted towards the center of the screen. 

It looks like an issue with `wl-copy`, but I have no idea where to look for the root cause of this. Do you have any insight on this issue?

**Comment by Drakulix** [comment]
The root cause of this is likely coming from the fact, that `wl-copy` will spawn a transparent window to obtain window focus, which is required to read clipboard contents.

In more details:
1. `wl-clipboard` will try to use the `wlr-data-control` protocol to access or set clipboard contents.
  - This protocol basically enables every application to freely access the clipboard as long as it has access to the wayland-socket.
  - While access can be restricted, there is currently no infrastructure to limit it for example to *only* `wl-copy` and `wl-paste`. As such cosmic-comp decides against supporting this protocol for the associated security risk at the moment.
2. Failing to bind `wlr-data-control` it can access the clipboard like any other client, but that requires a handle to a window, that has focus.
  - As such `wl-copy` will spawn a window with `xdg-shell`, hoping the compositor gives new windows focus immediately. So even this approach relies on implementation-defined behaviour and we should actually re-consider "*supporting*" focus stealing in cosmic-comp.
  - Given a new window is spawned cosmic-comp will take the currently active fullscreen window out of that state. Which is desired behaviour on our side. This is the bug you are seeing.
  - The transparent/invisible `wl-copy` window will get focus, at which point `wl-copy` will store the new contents in the clipboard and unmaps the window again.
  - Alacritty regains focus - being the previously focused window - but is not fullscreen anymore.

**Sidenote**: If cosmic-comp would never give focus to wl-copy, the program would give up and not work at all.

The next question is what to do about this issue... which is not that easy to figure out, because cosmic-comp essentially made the concious decision to not support this use-case. And wl-clipboard's workaround causes unexpected side-effects, which is not really cosmic's fault either.

I'll have to get back to you on a proper solution:
- We *could* in theory build a workaround *just* for wl-copy, but in practice other applications (like `wl-clipboard-rs`) are likely suffering the same problem.
- Maybe we can provide a `wlr-data-control`-implementation (which would be a proper solution), but have it disabled by default. That way we could provide a toggle to allow "any application to freely access clipboard contents", which would allow running wl-clipboard at the expanse of security.
- A better solution would be, if alacritty would have a way to programmatically access the clipboard contents on behalf of a running command line client, given alacritty is controlling the window, that actually has focus here and is allowed to access the clipboard contents normally (like through `Ctrl+Shift+C`).
Given alacritty is a cross-platform application, I am not sure how keen their devs would be to implement some custom control-codes or something similar to facilitate such functionality specific to wayland though.

**Comment by xDarksome** [comment]
Ok, so if understand this correctly, the main issue is the fact that Helix don't actually have a window. So this is a generic problem of "headless" processes?

I see the security implications, haven't thought about them before. I think, ideally, there should be a confirmation pop up when pasting from the clipboard for both "headful"/"headless" usecases.
Current state of `wayland` clipboard affairs seems like a half-baked solution to me. I would rather have a separate "secure" clipboard with a full ritual of ensuring that no other process can steal the buffer. But I'm not a protocol designer :upside_down_face: 

> Maybe we can provide a wlr-data-control-implementation (which would be a proper solution)

This seems like the most reasonable solution. Is it hard to implement?

> A better solution would be, if alacritty would have a way to programmatically access the clipboard contents on behalf of a running command line client

Even if we could persuade Alacritty devs to do something like that, there are also a plethora of other terminal emulators in the wild. 

From my "user" perspective I would rather just allow all applications to access the default system clipboard (as you've said as a configuration option) and then implement some secure buffer for passwords / public keys copypasting. Theoretically, it could be a separate application.

**Comment by xDarksome** [comment]
Realistically, though, if you are a linux desktop user and your threat model includes scenario of some running app stealing your clipboard, then you are already f*ckd. :laughing: 

Linux app compartmentalisation is still not there yet. If you have a running rogue app on your system, the system clipboard security may be the least of your problems.

**Comment by Drakulix** [comment]
> I think, ideally, there should be a confirmation pop up when pasting from the clipboard for both "headful"/"headless" usecases.

Every time? This is definitely doable, but it seems a little annoying to me, but maybe this could be the default, if access is not generally allowed.
Unfortunately there is no way we can "authenticate" a particular binary, without making it possible for other applications to mimic said binary.

> Current state of wayland clipboard affairs seems like a half-baked solution to me. I would rather have a separate "secure" clipboard with a full ritual of ensuring that no other process can steal the buffer. But I'm not a protocol designer.

This is easier said then done. The core protocol relies on focus to allow access, which is a very reasonable assumption... for GUI applications. "Headless"-apps simply don't have a similar property, that we can restrict.
But if a "ritual" is an acceptable solution, we definitely *could* implement a confirmation dialog.

> From my "user" perspective I would rather just allow all applications to access the default system clipboard (as you've said as a configuration option) and then implement some secure buffer for passwords / public keys copypasting. 

The latter for passwords/public-keys is again difficult without changing every password-manager in existence. Just like we can't convince every terminal emulator in existence.

> This seems like the most reasonable solution. Is it hard to implement?

No, not really. Somebody just has to do it and I am afraid it is not particularly high on my priority list. I can give you some hints, if you feel like tackling this yourself.

**Comment by xDarksome** [comment]
> Unfortunately there is no way we can "authenticate" a particular binary, without making it possible for other applications to mimic said binary.

> The latter for passwords/public-keys is again difficult without changing every password-manager in existence. Just like we can't convince every terminal emulator in existence.

I think mimicking may not be a problem. Imagine we have a list of applications (binary/process/app_id names, whatever) for which we say that every copy operation performed in the context of these apps should be followed by a "secure" paste operation.

So, when I'm copying some data from my password manager, pasting this data always requires explicit user confirmation.

And the worst thing that can be done by a fake application is triggering "secure" paste on some useless data.
There is also an issue of a fake app being able to overwrite the current state of the "secure" clipboard (ex. replacing crypto wallet address), in which case we should also prompt on copy operations.

> No, not really. Somebody just has to do it and I am afraid it is not particularly high on my priority list. I can give you some hints, if you feel like tackling this yourself.

Please, do. I need this feature, and I am very eager to switch to Rust-based compositor. :smile:

**Comment by jokeyrhyme** [comment]
> Xwayland applications can't be supported by this proposition, as they are all represented by a single client.

I don't mean to derail the conversation too much, but I'm curious why I've never seen a compositor provide a separate instance of Xwayland for each X11 app/process? Because doing so would allow for consistent per-client granularity, but maybe this is horrible in terms of usage of system resources?

**Comment by Drakulix** [comment]
> I don't mean to derail the conversation too much, but I'm curious why I've never seen a compositor provide a separate instance of Xwayland for each X11 app/process?

Mostly because the integration between Xwayland applications becomes annoying to deal with in that case. All lot of communication is still handled internally by Xwayland, like Drag&Drop just to give one example. All of that would have to be proxied between the instances by the compositors, which is just a lot of work, if you want a comparable experience.
Nothing prevents this fundamentally though and I have certainly thought about this idea. System resources might be a bottleneck though, especially RAM.
